### ISSUE TITLE
Loss of Character Alignment

### ISSUE THREAD

**Issue by yipidee** [yipidee/silab#1]
Message renders fine in app, maintains spacing for sending in Gmail, but loses alignment when rendered on other device or browser.

@surrealmccoy

**Comment by yipidee** [comment]
Going to attempt creating image from TextView and sharing it instead of String literal as it ensures same layout on all devices. Will however become an attached image.

**Comment by yipidee** [comment]
Committed version that sends images. Thoughts @surrealmccoy?

**Comment by yipidee** [comment]
Limit on image height, medium length messages cannot be handled

**Comment by surrealmccoy** [comment]
'Limit on image height' from where exactly?

**Comment by surrealmccoy** [comment]
And to what 'image' are you referring, exactly?

**Comment by yipidee** [comment]
Such is your involvement in the outrigger that while ideas and be formed, tested and dumped without you noticing...

There was a feature to send the emojified text as an image rather than as text. But the image quickly becomes too tall.

**Comment by yipidee** [comment]
Outrigger = project
While = whole

**Comment by surrealmccoy** [comment]
That was ages ago sure! Before I put an end to your notion of
sending images with my hard graft and research into white space
character-combinations that worked on both iOS and Android.
"Here, McCoy, A wos just thinkin thur, we'll not be fit to send
an Emojified message that looks good on both phones, sher we should
just send the messages as images!".
Where would ye get it!

On Tuesday, July 14, 2015, yipidee notifications@github.com wrote:

> Such is your involvement in the outrigger that while ideas and be formed,
> tested and dumped without you noticing...
> 
> There was a feature to send the emojified text as an image rather than as
> text. But the image quickly becomes too tall.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yipidee/silab/issues/1#issuecomment-121234560.

## 

Cathal.

**Comment by yipidee** [comment]
Going to close this issue, as the space combinations seem to have done the trick.
